### ISSUE TITLE
EnvironmentLocationNotFound error for installation on HPC with sudo rights

### ISSUE THREAD

**Issue by joao1980** [jolespin/veba#113]
Thanks for the tool. I am currently trying to test it. I am working on a HPC without sudo rights. Having said that, I managed to install all modules by setting my conda environments to a specific folder. However, when I try to run , e.g., annotate, it fails.

EnvironmentLocationNotFound: Not a conda environment: /xxx/global/software/skylake/software/Mamba/23.3.1-1/envs/VEBA-annotate_env

Traceback (most recent call last):
  File "/home/xxx/.conda/envs/VEBA/bin/annotate.py", line 10, in <module>
    from genopype import *
ModuleNotFoundError: No module named 'genopype'

I'm guessing this will happen no matter the module. How can I fix this?
Thanks in advance.
Cheers,
Joao

**Comment by jolespin** [comment]
Looks like the environment creation failed.  I've seen similar situations happen on lab-specific HPCs that aren't managed by an institute.

A few questions: 
* Do you have SLURM/SunGridEngine on here or do you run everything on the head node? 
* How much memory was allocated during the installation?
* Can you provide the error message? 

If you have sudo rights then you might want to consider using the Docker workflow. 

https://github.com/jolespin/veba/blob/main/walkthroughs/docs/adapting_commands_for_docker.md
https://www.youtube.com/watch?v=3aFV-3rsJ5w&t

**Comment by jolespin** [comment]
Feel free to reopen if this issue persists
