### ISSUE TITLE
[Bug] small bug on install.sh

### ISSUE THREAD

**Issue by nicolazarte** [jolespin/veba#127]
**Describe the bug:**
On install.sh the environments don't get installed and the process is idle forever. 

Solved by adding -y to the environment creation line:

(mamba env create -y -f $ENV_YAML -p ${CONDA_ENVS_PATH}/${ENV_NAME} || echo "Error when creating VEBA environment: ${ENV_YAML}" ; exit 1) &> ${LOG_DIRECTORY}/${ENV_NAME}.log

**Comment by jolespin** [comment]
Interesting I haven't had this before. Are you using the newest release and did you make sure to follow the step 0 parts where you clean up environment and add conda channels in config?

**Comment by jolespin** [comment]
Let me know if this issue still persists and I'll reopen.

**Comment by jarrodscott** [comment]
FYI I just tried to install the latest version of `veba`  (VEBA_v2.4.2 ) and received an error saying the flag `-y` is not a valid option for `mamba env create in `[line 55 of install.sh](https://github.com/jolespin/veba/blob/4ac6dab9866684c90942dbf5a9ea3b3568e2c2bb/install/install.sh#L55). Once I removed the `-y` flag from that line the installation completed without issue.

**Comment by jolespin** [comment]
it must have an old mamba.  `-y` was introduced in later versions.
