### ISSUE TITLE
[Typo] Typo in installation README.md

### ISSUE THREAD

**Issue by erfanshekarriz** [jolespin/veba#14]
Hi Josh, 

Just a quick fix to make at https://github.com/jolespin/veba/blob/main/install/README.md

The new version directory is ```veba-1.0.3d``` so ```cd veba/install``` doesn't work. Might be useful for future versions and development to make it more implicit with something like cd ${VERSION_TAG}/install

Also has issues on 
``` 
# Update the permissions
chmod 755 veba/src/*.py
chmod 755 veba/src/scripts/*
```

Best, 

Erfan

**Comment by jolespin** [comment]
Moved the `v` out of the version and made some minor adjustments.  It works now, including the chmod commands.  Thanks for catching this. 

Fixed in this commit: https://github.com/jolespin/veba/commit/f2095b62c60eca18d95856e917b54ef2abd5332c

Reopen if it's still giving you trouble.
