### ISSUE TITLE
[Feature Request] Add checkpoint after 1__assembly assembly (before index building)

### ISSUE THREAD

**Issue by erfanshekarriz** [jolespin/veba#18]
Hi Josh, 

In my last bug report, I saw that biopython was missing. All my assemblies were finished but the 1__assembly step wasn't followed through because of the missing module. 

If I re-run the `assembly.py` command, it will start assembling from scratch. 

I was wondering if there could be a checkpoint in the Genopype right after assembly is done. My assembly took around 4 days and now I have to run it again because the first step of the 1__assembly checkpoint is to remove all previous files. 

Would appreciate it if an extra checkpoint could be added right after assembly! 

Best, 

Erfan

**Comment by jolespin** [comment]
This is a good thing I can add to the FAQ.  I deal with this all the time in my prototyping. 

What I do is the following:
1) From the commands.sh, run the rest of the command that is needed for the step you stalled 

2) Create a non-empty file in the checkpoint directory for that step (it can have anything in it, I usually do the time stamp but you could do anything).  It should be veba_output/assembly/(sample_id)/checkpoints/1__assembly

Then rerun the module, it should pick up from that point.

Let me know if that works.  

>

**Comment by erfanshekarriz** [comment]
I've done exactly that for the rest of my samples, but unfortunately one sample was sacrificed. If it could be automatically handled then I think that's even better, but understand that there are pros and cons to doing that. 

Best, 

Erfan

Erfan

**Comment by jolespin** [comment]
Do you happen to have snapshots on your machine?  On our server its, “cd .snapshot” within a directory. It could be worth contacting IT to see if your server has an equivalent.

**Comment by erfanshekarriz** [comment]
Unfortunately no. Our server is a private one only for a small bioinformatics team and is managed internally by my colleague. Not to worry though, personally not in a rush! 

Best, 

Erfan

**Comment by jolespin** [comment]
I just tested this and with SPAdes at least, you can start from where you left off in the assembly didn't finish.  I'm not sure how this works with a finished assembly. 

I added to the [FAQ](https://github.com/jolespin/veba/blob/main/FAQ.md)

**28. While running assembly.py my job errored (e.g., timed out or ran out of memory), how can I resume the assembly without starting over?**

If you're using a SPAdes-based program (e.g., metaSPAdes) you can use the following option: --assembler_options='--restart-from last'.

For example, the following assembly.py command: source activate VEBA-assembly_env && assembly.py -1 ${R1} -2 ${R2} -n ${ID} -o ${OUT_DIR} -p ${N_JOBS} --assembler_options='--restart-from last'

I'm not too familar with MEGAHIT but if there is a similar option, I'll add it in there. 

The mid-step checkpoint can get really tricky and I don't know if adding one specifically for one step in one module would be a good idea.  Though, to get around this particular edge case you can always run part of the code in the `command.sh` then manually create the checkpoint file. 

Check out number 29 in the [FAQ](https://github.com/jolespin/veba/blob/main/FAQ.md).
