### ISSUE TITLE
misspelling itermediate -> intermediate

### ISSUE THREAD

**Issue by hyphaltip** [jolespin/veba#2]
https://github.com/jolespin/veba/blob/03fefe90a463725004c5d10af1fccbc960f14df3/src/binning-eukaryotic.py#L221

**Comment by jolespin** [comment]
Thanks for catching this. I'll fix it in the next couple of hours when I get to my computer.

**Comment by jolespin** [comment]
Fixed it in the commit from a few hours ago: https://github.com/jolespin/veba/commit/7c5addf9ed6e8e45502274dd353f20b211838a41

I'll update the release version next.
