### ISSUE TITLE
[Question] ERROR: Paired-end reads were detected in single-end read library" at the featurecounts step. How do I indicate that there are paired-end r

### ISSUE THREAD

**Issue by MACampbell91** [jolespin/veba#22]
Hi Josh,

During viral binning, I am getting this error "ERROR: Paired-end reads were detected in single-end read library" at the featurecounts step. How do I indicate that there are paired-end reads.

Cheers,

Matt

**Comment by jolespin** [comment]
Oh that's weird! Can you go to one of your samples in the preprocess folder then head the cleaned_1.fastq.gz and cleanes_2.fastq.gz?

Can I see what those look like?

**Comment by MACampbell91** [comment]
Here you go:

cleaned_1.fastq.gz

@NB500898:122:HYLMKBGXC:1:11105:19415:1375 1:N:0:GTCTCTAC+GTCCTTAC
GTGCGCCAGCGCCGCTGGCTGCCGAGGACGCCGACCAGGATCTCCAGCATGTAGGTGTAAGCGCCGAACGGCCGGCGTCCGGCACTGGCCAGGCTACCGACACGTAAAAAGGGAAGATAACCTCGGTGCCGTTCTGCGGGTCGGCCGCGCG
+
AAAAAEE/EEEEEEEEEEEEEEEEAEE6EEEEE6EEEEE6EEEAE/EEEEE<EEEEEEEAEEEEEEEAE/EEEEEEEEEEEEA/EAEE/</AE/A/</</E//<////<A//<///////<E/EE///A6AE6////<A6//A/E6/A<6/
@NB500898:122:HYLMKBGXC:1:11105:10521:1380 1:N:0:GTCTCTAC+GTCCTTAC
GGGGCGGCGAGGCGAGATAATTGGCCTGGACGAGCGGGTGGATGCGGCCCTCGAAGTTGCGGTTGCCCCCGAGAGCACGCCCGC
+
AAAAAEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEA</AA/A/EEEEEEEEEE
@NB500898:122:HYLMKBGXC:1:11105:10663:1382 1:N:0:GTCTCTAC+GTCCTTAC
GTAAGGGGTGCAGCCTTTTACGCTGAGTCGTCGAATCGCCCGTTCTGTTAATATTTTGTTTTGAAAGGCCAACCGCCCGACAGCACCACCTGAGAGAGGTTTGCCCGCTGGACGATGCCTTCTATGATGTCGCTCAGCGTATTGTGAAAAT

and

cleanes_2.fastq.gz

@NB500898:122:HYLMKBGXC:1:11105:19415:1375 2:N:0:GTCTCTAC+GTCCTTAC
CTCGTTACCTGACCGCCTACCAGTTGGGGCACGTCGACGGCGTCTGGGAGCCGTTTTTCGCCGGCAGCGCGGCCGACCCGCAGAACGGCTCCGCGAAGATCCTCGACTCGTTCTGGTCCGAAGCCCCGCCTCTTACGCACGGCGACGGCAG
+
AAAAAEEEEEEEE/EEEEAEEEEA<6EE/EEE/EE6E</EEEEE</EE/E/EE<AE<A6E/EEEEEE</E///AEAA<AEE/</AA66//666////AEE////////////A//<E</A/AE<6//A/E/E///6//<////6///////
@NB500898:122:HYLMKBGXC:1:11105:10521:1380 2:N:0:GTCTCTAC+GTCCTTAC
CCGCGGGCGTGCTCTCGGGCAACCGCAACATCGAGGGCCGCATCCACCCGCTCGTCCAGGCCAATTATCTCGCCTCGCCGACCC
+
AAAAAEAEEAEAAEEE/EEE6AEEEEAEE6AEE<EEE/AAA//EAA/EE/E</A/EA/EEE/E</<<//<66A<A/AA/E/AE<
@NB500898:122:HYLMKBGXC:1:11105:10663:1382 2:N:0:GTCTCTAC+GTCCTTAC
GGCCAGGCCGCCAGCGCGCTCGAATTTGCTGCCGCCCGCTCTAGCGAAAAAGGCCGCTAACCCTTTGCAAGCACCCGTCTTTCGACCAGCCAGAATGACTGGAGGCGCTGCCTAGGCCGCGACGTGCATTGAGGCTCGACAGCTCTAGAC

**Comment by jolespin** [comment]
So I'm on vacation until next Wednesday and will get to this asap but in the meantime, can you check out some of these threads?

https://www.biostars.org/p/9533564/#9533588

Also, can you run:

samtools view mapped.sorted.bam | head

https://www.biostars.org/p/178730/

**Comment by MACampbell91** [comment]
Hi Josh,

I should of mentioned this before.... The same issue occurs with the kingfisher data (see attached). 

Is there anyway in Veba to indicate that it is paired-end? I tried a few things with --featurecounts_options based on http://bioinf.wehi.edu.au/featureCounts/, however they use "-p" to indicate paired-end reads which isn't recognised by VEBA. 

[4__featurecounts.e.txt](https://github.com/jolespin/veba/files/11147303/4__featurecounts.e.txt)

**Comment by jolespin** [comment]
Check out number 38 here: https://github.com/jolespin/veba/blob/main/FAQ.mdTry using --featurecounts_options=“-p” Sent from my iPhoneOn Apr 4, 2023, at 3:19 AM, Matthew Arthur Campbell ***@***.***> wrote:﻿
Hi Josh,
I should of mentioned this before.... The same issue occurs with the kingfisher data (see attached).
Is there anyway in Veba to indicate that it is paired-end? I tried a few things with --featurecounts_options based on http://bioinf.wehi.edu.au/featureCounts/, however they use "-p" to indicate paired-end reads which isn't recognised by VEBA.
4__featurecounts.e.txt

**Comment by MACampbell91** [comment]
That worked perfectly. I used --featurecounts_options='-p'.

Thanks for your help.

**Comment by jolespin** [comment]
Awesome! When you get some time can you give me some insight on what May have caused this? You used paired end reads but it didn't detect them? It'll be good for my records and the FAQ. Thanks!

**Comment by MACampbell91** [comment]
So whilst running the viral binning module an issue occurred during step 4__featurecounts stating this "ERROR: Paired-end reads were detected in single-end read library". To fix the issue --featurecounts_options='-p' must be added to the run script. I would assume that all the input data would be paired-end, so perhaps you could add the option above as a default? I am not sure why its not working in my system as it obviously working with yours. When you are running this module, does it read it as single or paired?

I now have an issue with the VEBA-binning-prokaryotic module. When it gets to 7_dastool, I get this error "/bin/sh: 1: Syntax error: redirection unexpected". Do you want me to start a new issue thread?

**Comment by jolespin** [comment]
Yea by default, if running the end-to-end pipeline paired end is mandatory but I also want to support long reads based contigs which will be considered single ended.  What I'll do is add -p by default unless --single_ended is provided as an argument. 

Can you start a new issue for this one?  Also, if you can provide your scaffolds and mapped.sorted.bam I can help diagnose. I just got back in town so I'll have a lot more time.

**Comment by jolespin** [comment]
```
VEBA-mapping_env.yml:  - subread=2.0.1=h5bf99c6_1
VEBA-assembly_env.yml:  - subread=2.0.1=h7132678_2
VEBA-binning-eukaryotic_env.yml:  - subread=2.0.1=h7132678_2
VEBA-binning-viral_env.yml:  - subread=2.0.3=h7132678_1
VEBA-binning-prokaryotic_env.yml:  - subread=2.0.1=h7132678_2
```

VEBA-binning-viral_env.yml uses the most recent version of featureCounts and it looks like this functionality is added. https://www.biostars.org/p/9561574/#9561638

**Comment by aida999-prog** [comment]
I was having the same issue and adding the option "-p'" fixed the problem!! Thanks!!
