### ISSUE TITLE
VEBA-binning-prokaryotic module - step 7_dastool error: /bin/sh: 1: Syntax error: redirection unexpected

### ISSUE THREAD

**Issue by MACampbell91** [jolespin/veba#23]
Hi Josh,

Whilst running the VEBA-binning-prokaryotic module, I get this error at step 7_dastool -  /bin/sh: 1: Syntax error: redirection unexpected.

Not sure if this is an issue with my set up or with the script running dastool?

Here's a link to the scaffolds.fasta and mapped.sorted.bam files from sample SRR17458603: https://www.dropbox.com/sh/fcjjkcojsvthh2a/AABHfFUupdUbdj7y7VSHeAuJa?dl=0

Cheers

**Comment by jolespin** [comment]
Testing it right now.  Can you send me the commands you used and the log file?

**Comment by MACampbell91** [comment]
I run the command in a .sh file shell script as seen below:

N_JOBS=4
N_ITER=10

# This is the default output
OUT_DIR=veba_output/binning/prokaryotic/

for ID in $(cat identifiers.list); do
        N="binning-prokaryotic__${ID}";
        rm -f logs/${N}.*

        # Get the assembly and bam files
        FASTA=veba_output/binning/viral/${ID}/output/unbinned.fasta
        BAM=veba_output/assembly/${ID}/output/mapped.sorted.bam

        binning-prokaryotic.py -f ${FASTA} -b ${BAM} -n ${ID} -p ${N_JOBS} -o ${OUT_DIR} -m 1500 -I ${N_ITER}

done

Here are the log files and unbinned.fasta file
https://www.dropbox.com/sh/fcjjkcojsvthh2a/AABHfFUupdUbdj7y7VSHeAuJa?dl=0

**Comment by jolespin** [comment]
Thanks for sending these over.  So a few things: 
1) There are definitely bins in here.  I'm going to finish the run and upload them for you here.  For iteration 1 at least there are a couple, I suspect we MIGHT get 1 or 2 more in the next couple of iterations but it looks like iteration 1 picked up most of it: 

<img width="720" alt="image" src="https://user-images.githubusercontent.com/9061708/230442323-a6811aee-efc4-4273-93ce-5f422bc97f35.png">

2) It looks like there is something wrong with your install.  Can you go to the veba repository that you downloaded and then upload the log file for the prokaryotic binning module? If you're in the veba repository downloaded from GitHub then it would be this: `install/environments/VEBA-binning-prokaryotic_env.yml.log`

3) Depending on whether or not that installed correctly we can diagnose further.  I suspect there was an error.  If not, then run the following (Note: This is all assuming you're IN the veba repository you downloaded from GitHub): 

3.1) Run step 0: https://github.com/jolespin/veba/tree/main/install#install
3.2) Remove the binning environment: `mamba env remove -n VEBA-binning-prokaryotic_env`
3.3) Reinstall the environment BUT make sure you are allocation ~16GB of memory to be safe because CheckM2 runs some code in the backend and will likely crash the head node.  I usually do this in an interactive SLURM session. `mamba env create -n VEBA-binning-prokaryotic_env -f install/environments/VEBA-binning-prokaryotic_env.yml` 
3.4) Patch up your install by first copying the script files into bin: bash install/update_environment_scripts.sh .` Don't forget to include the `.` because this specifies you're IN the repository you want to use for the files. 
3.5) Finish up your patch by creating activate/deactivate scripts along with setting/unsetting necessary environment variables: `bash install/update_environment_variables.sh /path/to/veba_database`

Let me know if you have any issues!

**Comment by jolespin** [comment]
[output_without_unbinnedfasta.zip](https://github.com/jolespin/veba/files/11173172/output_without_unbinnedfasta.zip)

**Comment by MACampbell91** [comment]
Thanks for the output.

After following the reinstallation of the module, I am still getting the same error at step 7_dastool error: /bin/sh: 1: Syntax error: redirection unexpected.

[VEBA-binning-prokaryotic_env.yml.log](https://github.com/jolespin/veba/files/11180222/VEBA-binning-prokaryotic_env.yml.log)

**Comment by jolespin** [comment]
Interesting.  It looks like the install completed without error. What happens if you do DAS_Tool -h from the VEBA-binning-prokaryotic_env?

**Comment by MACampbell91** [comment]
DAS_Tool -h works and provides the normal documentation .

I am trying to figure out what's causing this syntax issue when it starts DAS_Tool. Could there be some incompatible code? The script may contain code that is incompatible with the shell being used which should just be bash, right? If the script uses Bash-specific features but is somehow run with "sh", it may cause errors.

**Comment by jolespin** [comment]
Interesting! Hmm do you know if bash is your default shell once you submit to the grid?

https://unix.stackexchange.com/questions/569950/syntax-error-redirection-unexpected

Can you submit a job to your grid to tells you what shell your using? 

https://stackoverflow.com/questions/3327013/how-to-determine-the-current-interactive-shell-that-im-in-command-line

**Comment by MACampbell91** [comment]
Checked my default shell and it is /bin/bash.

Is there any scripts that might be using the shebang line #!/bin/sh instead of #!/bin/bash?
Another thing from what I have read, a common cause of this error message is when there are errors in the syntax of redirection commands in the script. For example, if you are using the ">" or ">>" operators to redirect output to a file, you may encounter this error if there are errors in the syntax of the redirection command.

**Comment by jolespin** [comment]
Can you try copy and pasting the DAS Tool command (just the DAS Tool call) from the commands.sh? If you upload your commands.sh file or copy the line I can tell you which part to run to make it easier.  If this works, then it must be the way I'm using `subprocess` where it's using /bin/sh instead of /bin/bash.

**Comment by MACampbell91** [comment]
Here you go:
# 7__dastool
S2B=$(python /home/ubuntu/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/scripts/check_scaffolds_to_bins.py -i S3_bin/S3/intermediate/3__binning_metabat2/scaffolds_to_bins.tsv,S3_bin/S3/intermediate/4__binning_maxbin2-107/scaffolds_to_bins.tsv,S3_bin/S3/intermediate/5__binning_maxbin2-40/scaffolds_to_bins.tsv,S3_bin/S3/intermediate/6__binning_concoct/scaffolds_to_bins.tsv -n metabat2,maxbin2-107,maxbin2-40,concoct) && IFS=" " read -r -a S2B_ARRAY <<< "$S2B" && /home/ubuntu/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/DAS_Tool --bins ${S2B_ARRAY[0]} --contigs veba_output/assembly/SRR17458603/intermediate/1__assembly/scaffolds.fasta --outputbasename S3_bin/S3/intermediate/7__dastool/_ --labels ${S2B_ARRAY[1]} --search_engine diamond --score_threshold 0.1 --write_bins 1 --create_plots 0 --threads 1 --proteins S3_bin/S3/intermediate/2__prodigal/gene_models.faa --debug  && cat S3_bin/S3/intermediate/7__dastool/__DASTool_bins/*.fa | /home/ubuntu/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/seqkit seq -m 3000 > S3_bin/S3/tmp/scaffolds.binned.gte3000.fasta && mkdir -p S3_bin/S3/intermediate/7__dastool/consensus_domain_classification && mkdir -p S3_bin/S3/intermediate/7__dastool/__DASTool_bins/eukaryota && /home/ubuntu/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/tiara -i S3_bin/S3/tmp/scaffolds.binned.gte3000.fasta -o S3_bin/S3/intermediate/7__dastool/consensus_domain_classification/tiara_output.tsv --probabilities -m 3000 -t 1  && python /home/ubuntu/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/scripts/consensus_domain_classification.py -i S3_bin/S3/intermediate/7__dastool/__DASTool_scaffolds2bin.txt -t S3_bin/S3/intermediate/7__dastool/consensus_domain_classification/tiara_output.tsv -o S3_bin/S3/intermediate/7__dastool/consensus_domain_classification --logit_transform softmax && for ID_GENOME in $(cat S3_bin/S3/intermediate/7__dastool/consensus_domain_classification/eukaryota.list); do mv S3_bin/S3/intermediate/7__dastool/__DASTool_bins/${ID_GENOME}.* S3_bin/S3/intermediate/7__dastool/__DASTool_bins/eukaryota; done && cat S3_bin/S3/intermediate/7__dastool/__DASTool_bins/eukaryota/*.fa | grep "^>" | cut -c2- > S3_bin/S3/intermediate/7__dastool/__DASTool_bins/eukaryota/eukaryota.scaffolds.list && cat S3_bin/S3/intermediate/7__dastool/__DASTool_scaffolds2bin.txt | grep -v -f S3_bin/S3/intermediate/7__dastool/__DASTool_bins/eukaryota/eukaryota.scaffolds.list > S3_bin/S3/intermediate/7__dastool/__DASTool_scaffolds2bin.no_eukaryota.txt && cut -f1 S3_bin/S3/intermediate/7__dastool/__DASTool_scaffolds2bin.no_eukaryota.txt > S3_bin/S3/intermediate/7__dastool/binned.list && python /home/ubuntu/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/scripts/partition_gene_models.py -i S3_bin/S3/intermediate/7__dastool/__DASTool_scaffolds2bin.no_eukaryota.txt -g S3_bin/S3/intermediate/2__prodigal/gene_models.gff -d S3_bin/S3/intermediate/2__prodigal/gene_models.ffn -a S3_bin/S3/intermediate/2__prodigal/gene_models.faa -o S3_bin/S3/intermediate/7__dastool/__DASTool_bins --use_mag_as_description && rm -rf S3_bin/S3/intermediate/7__dastool/_.seqlength S3_bin/S3/tmp/scaffolds.binned.gte3000.fasta

**Comment by MACampbell91** [comment]
Here you go:

# 7__dastool
S2B=$(python /home/ubuntu/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/scripts/check_scaffolds_to_bins.py -i veba_output/binning/prokaryotic/SRR17458603/intermediate/3__binning_metabat2/scaffolds_to_bins.tsv,veba_output/binning/prokaryotic/SRR17458603/intermediate/4__binning_maxbin2-107/scaffolds_to_bins.tsv,veba_output/binning/prokaryotic/SRR17458603/intermediate/5__binning_maxbin2-40/scaffolds_to_bins.tsv,veba_output/binning/prokaryotic/SRR17458603/intermediate/6__binning_concoct/scaffolds_to_bins.tsv -n metabat2,maxbin2-107,maxbin2-40,concoct) && IFS=" " read -r -a S2B_ARRAY <<< "$S2B" && /home/ubuntu/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/DAS_Tool --bins ${S2B_ARRAY[0]} --contigs veba_output/binning/viral/SRR17458603/output/unbinned.fasta --outputbasename veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/_ --labels ${S2B_ARRAY[1]} --search_engine diamond --score_threshold 0.1 --write_bins 1 --create_plots 0 --threads 4 --proteins veba_output/binning/prokaryotic/SRR17458603/intermediate/2__prodigal/gene_models.faa --debug  && cat veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/__DASTool_bins/*.fa | /home/ubuntu/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/seqkit seq -m 3000 > veba_output/binning/prokaryotic/SRR17458603/tmp/scaffolds.binned.gte3000.fasta && mkdir -p veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/consensus_domain_classification && mkdir -p veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/__DASTool_bins/eukaryota && /home/ubuntu/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/tiara -i veba_output/binning/prokaryotic/SRR17458603/tmp/scaffolds.binned.gte3000.fasta -o veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/consensus_domain_classification/tiara_output.tsv --probabilities -m 3000 -t 4  && python /home/ubuntu/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/scripts/consensus_domain_classification.py -i veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/__DASTool_scaffolds2bin.txt -t veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/consensus_domain_classification/tiara_output.tsv -o veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/consensus_domain_classification --logit_transform softmax && for ID_GENOME in $(cat veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/consensus_domain_classification/eukaryota.list); do mv veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/__DASTool_bins/${ID_GENOME}.* veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/__DASTool_bins/eukaryota; done && cat veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/__DASTool_bins/eukaryota/*.fa | grep "^>" | cut -c2- > veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/__DASTool_bins/eukaryota/eukaryota.scaffolds.list && cat veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/__DASTool_scaffolds2bin.txt | grep -v -f veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/__DASTool_bins/eukaryota/eukaryota.scaffolds.list > veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/__DASTool_scaffolds2bin.no_eukaryota.txt && cut -f1 veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/__DASTool_scaffolds2bin.no_eukaryota.txt > veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/binned.list && python /home/ubuntu/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/scripts/partition_gene_models.py -i veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/__DASTool_scaffolds2bin.no_eukaryota.txt -g veba_output/binning/prokaryotic/SRR17458603/intermediate/2__prodigal/gene_models.gff -d veba_output/binning/prokaryotic/SRR17458603/intermediate/2__prodigal/gene_models.ffn -a veba_output/binning/prokaryotic/SRR17458603/intermediate/2__prodigal/gene_models.faa -o veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/__DASTool_bins --use_mag_as_description && rm -rf veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/_.seqlength veba_output/binning/prokaryotic/SRR17458603/tmp/scaffolds.binned.gte3000.fasta

**Comment by MACampbell91** [comment]
S2B_ARRAY didn't work, however giving the command the scaffolds_to_bins.tsv from steps 3-6 did work. Perhaps there's something with the S2B_ARRAY that causing the error on my system? 

Thanks for your help!

**Comment by jolespin** [comment]
Yes of course! I want to get this working for you.  It's interesting because there are a handful of users and I haven't seen this issue yet.  Very curious to what it could be. 

Ah, I missed the first part of the command:

```
S2B=$(python /home/ubuntu/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/scripts/check_scaffolds_to_bins.py -i veba_output/binning/prokaryotic/SRR17458603/intermediate/3__binning_metabat2/scaffolds_to_bins.tsv,veba_output/binning/prokaryotic/SRR17458603/intermediate/4__binning_maxbin2-107/scaffolds_to_bins.tsv,veba_output/binning/prokaryotic/SRR17458603/intermediate/5__binning_maxbin2-40/scaffolds_to_bins.tsv,veba_output/binning/prokaryotic/SRR17458603/intermediate/6__binning_concoct/scaffolds_to_bins.tsv -n metabat2,maxbin2-107,maxbin2-40,concoct)

IFS=" " read -r -a S2B_ARRAY <<< "$S2B"

/home/ubuntu/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/DAS_Tool --bins ${S2B_ARRAY[0]} --contigs veba_output/binning/viral/SRR17458603/output/unbinned.fasta --outputbasename veba_output/binning/prokaryotic/SRR17458603/intermediate/7__dastool/_ --labels ${S2B_ARRAY[1]} --search_engine diamond --score_threshold 0.1 --write_bins 1 --create_plots 0 --threads 4 --proteins veba_output/binning/prokaryotic/SRR17458603/intermediate/2__prodigal/gene_models.faa --debug
```

Also, can you run this from your grid?

```
hostnamectl
```

Here's my output: 
```
(base) [jespinoz@exp-15-01 SOLEXASEQ-1680]$ hostnamectl
   Static hostname: exp-15-01
         Icon name: computer-server
           Chassis: server
        Machine ID: 6af4cf7b97e6476c9b6bf13f2892ddf1
           Boot ID: 2debec1ff8cf441b8b4c5ec29b0c7ec0
  Operating System: Rocky Linux 8.5 (Green Obsidian)
       CPE OS Name: cpe:/o:rocky:rocky:8:GA
            Kernel: Linux 4.18.0-348.23.1.el8_5.x86_64
      Architecture: x86-64
```

**Comment by MACampbell91** [comment]
With that first part added, the command worked perfectly.

Here's my hostnamectl output:

Static hostname: wa-geomicrobiomes
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 262c57b79c2546aca5fe9ad8b0fb0c7f
           Boot ID: 8531e1f5a6064586b6483c2fd57f3eb0
    Virtualization: kvm
  Operating System: Ubuntu 20.04.6 LTS
            Kernel: Linux 5.4.0-136-generic
      Architecture: x86-64

**Comment by jolespin** [comment]
Ok perfect that's good to know your DAS Tool is working as expected.  Can you try running that WHOLE long command? If this works then I think I know what's going on.

**Comment by MACampbell91** [comment]
It worked with the entire 7_Dastool command.

Okay great, let me know when you have updated genopype.

**Comment by jolespin** [comment]
Ok I think we just about nailed it down.  I suspect it has to do with defaults in the operating system that we can account for with a few adjustments. 

This should be one of the last requests.  

**Can you run an interactive queue on your HPC and run the following Python commands?**

>>> import subprocess
>>> subprocess.Popen("echo $0", shell=True) #If this hangs, just press return again
>>> subprocess.Popen("echo $0", shell=True, executable="/bin/bash") # Same with these
>>> subprocess.Popen("echo $0", shell=True, executable="/bin/sh")

Thanks for your patience. Basically, I wanna see the default shell for your system and if it changes. I just made the edits to genopype for the next beta.  I'm going to test it really quick and then give you instructions on updating it.  Think this should fix the issue.

**Comment by jolespin** [comment]
I updated the package and it includes some new bells/whistles. 

https://anaconda.org/jolespin/genopype

Can you update your `VEBA-binning-prokaryotic_env` with this version and rerun?

`conda install -c jolespin genopype==2023.4.13`

**Comment by MACampbell91** [comment]
Good news, the test data works now with the genopype update. Thanks for your help.

I will test my own data now and see how it goes. I will keep you updated.

**Comment by jolespin** [comment]
Awesome!  Can you let me know if it works for the sample you were having difficulty with?

**Comment by jolespin** [comment]
Please reopen if you encounter any more issues.
