### ISSUE TITLE
[Question] Why isn't `binning-eukaryotic.py` finding any eukaryotic bins and why are the output files empty?

### ISSUE THREAD

**Issue by franlat** [jolespin/veba#30]
Hello, I've been trying to run the `binning-eukaryotic.py` script on a small assembly to predict eukaryotic MAGs. However, the process fails every time, regardless of whether I try to do the binning with metabat2 or concoct. 

The input contigs are already predicted to be eukaryotic by whokaryote (a eukaryotic contig predictor that uses Tiara). I mapped the metagenomic samples with bwa-mem2 and used those sorted BAM files as input too.  Yet, the output files are empty except for the "unbinned.fasta". 

The output log file says:
```
Command:
echo '' > ../analyses/veba_eukaryotic_binning/binning/nano.G2/nano.G2/intermediate/1__binning_metabat2/scaffolds_to_bins.tsv && mkdir -p ../analyses/veba_eukaryotic_binning/binning/nano.G2/nano.G2/intermediate/1__binning_metabat2/bins && /opt/cesga/system/software/Core/veba-binning-eukaryotic_env/1.2.0/bin/coverm contig --threads 12 --methods metabat --bam-files ../analyses/veba_eukaryotic_binning/bam/nano.G2/PR173.nano.G2.euk.sorted.bam ../analyses/veba_eukaryotic_binning/bam/nano.G2/PR201.nano.G2.euk.sorted.bam ../analyses/veba_eukaryotic_binning/bam/nano.G2/PR217.nano.G2.euk.sorted.bam ../analyses/veba_eukaryotic_binning/bam/nano.G2/PR233.nano.G2.euk.sorted.bam ../analyses/veba_eukaryotic_binning/bam/nano.G2/PR249.nano.G2.euk.sorted.bam > ../analyses/veba_eukaryotic_binning/binning/nano.G2/nano.G2/intermediate/1__binning_metabat2/intermediate/coverage.tsv && /opt/cesga/system/software/Core/veba-binning-eukaryotic_env/1.2.0/bin/metabat2 -i ../data/coassembly_euk/nano.G2.corrected.fasta -o ../analyses/veba_eukaryotic_binning/binning/nano.G2/nano.G2/intermediate/1__binning_metabat2/bins/bin -a ../analyses/veba_eukaryotic_binning/binning/nano.G2/nano.G2/intermediate/1__binning_metabat2/intermediate/coverage.tsv -m 1500 -t 12 --minClsSize 2000000 --seed 1 --verbose 

Validating the following input files:
[=] File exists (830 MB): ../data/coassembly_euk/nano.G2.corrected.fasta
[=] File exists (2235 MB): ../analyses/veba_eukaryotic_binning/bam/nano.G2/PR173.nano.G2.euk.sorted.bam
[=] File exists (1832 MB): ../analyses/veba_eukaryotic_binning/bam/nano.G2/PR201.nano.G2.euk.sorted.bam
[=] File exists (3314 MB): ../analyses/veba_eukaryotic_binning/bam/nano.G2/PR217.nano.G2.euk.sorted.bam
[=] File exists (3013 MB): ../analyses/veba_eukaryotic_binning/bam/nano.G2/PR233.nano.G2.euk.sorted.bam
[=] File exists (3578 MB): ../analyses/veba_eukaryotic_binning/bam/nano.G2/PR249.nano.G2.euk.sorted.bam

Running. .. ... .....
Check log files to diagnose error:
cat ../analyses/veba_eukaryotic_binning/binning/nano.G2/nano.G2/intermediate/1__binning_metabat2/intermediate/log/1__binning_metabat2.*
No eukaryotic bins
```

And the metabat2 error log file:

```
ESC[33m[WARN]ESC[0m you may switch on flag -g/--remove-gaps to remove spaces
^MExecuting pipeline:   0%|          | 0/2 [00:00<?, ?it/s]^MExecuting pipeline:   0%|          | 0/2 [00:05<?, ?it/s]
cat: ../analyses/veba_eukaryotic_binning/binning/nano.G2/nano.G2/tmp/scaffolds_to_bins.tsv: No such file or directory
```
Metabat2 is executable and prints the help page when I load the veba environment, though. So it should work. 

I am running Veba 1.2.0 and here's the command that I used:

```
name=nano.G2
outbam=../analyses/veba_eukaryotic_binning/bam/${name}
coassembly=../data/coassembly_euk/${name}.corrected.fasta
outbin=../analyses/veba_eukaryotic_binning/binning/${name}

binning-eukaryotic.py -f ${coassembly} -b ${outbam}/*euk.sorted.bam -o ${outbin} -p 12 -n ${name}
```

The output file from the SLURM server I am working on gives me a bit more details, but I am still clueless:

```
^MExecuting pipeline:   0%|          | 0/5 [00:00<?, ?it/s]^MExecuting pipeline:   0%|          | 0/5 [00:18<?, ?it/s]
Traceback (most recent call last):
  File "/opt/cesga/system/software/Core/veba-database/1.2.0/veba-1.2.0/src/binning-eukaryotic.py", line 1116, in <module>
    main()
  File "/opt/cesga/system/software/Core/veba-database/1.2.0/veba-1.2.0/src/binning-eukaryotic.py", line 1111, in main
    pipeline.execute(restart_from_checkpoint=opts.restart_from_checkpoint)
  File "/opt/cesga/system/software/Core/veba-binning-eukaryotic_env/1.2.0/lib/python3.8/site-packages/genopype/genopype.py", line 804, in execute
    validate_file_existence(output_filepaths, prologue="\nValidating the following output files:", f_verbose=self.f_verbose, whitelist_empty_files=attrs["whitelist_empty_output_files"])
  File "/opt/cesga/system/software/Core/veba-binning-eukaryotic_env/1.2.0/lib/python3.8/site-packages/genopype/genopype.py", line 90, in validate_file_existence
    assert size_bytes >= minimum_filesize, "The following file appears to be empty ({} bytes): {}".format(size_bytes, path)
AssertionError: The following file appears to be empty (0 bytes): ../analyses/veba_eukaryotic_binning/binning/nano.G2/nano.G2/intermediate/1__binning_metabat2/scaffolds_to_bins.tsv
```

I do not know what I am doing wrong. Are my input files the problem? Or is it something to do with `genopype` ? The IT guys in my server had to install BioPython separately because it wasn't installed by default and it raised an error with some other modules, so maybe that messed up the whole installation?

**Comment by jolespin** [comment]
It seems like there aren't any eukaryotic bins from the error message but let's see what this file looks like: 

```
../analyses/veba_eukaryotic_binning/binning/nano.G2/nano.G2/intermediate/1__binning_metabat2/consensus_domain_classification/predictions.tsv
```

**Comment by franlat** [comment]
Thank you for the fast reply! 

I just checked and there are no directories within `1__binning_metabat2`, only files. All of them are empty, except for the `commands.sh` file. 
Here are the contents of `1__binning_metabat2`:

```
(base) [cseygflp@login209-18 1__binning_metabat2]$ ls -l
total 4
-rw-r--r-- 1 cseygflp csic    0 oct 22 21:34 binned.list
-rw-r--r-- 1 cseygflp csic    0 oct 22 21:34 bins.list
-rw-r--r-- 1 cseygflp csic 1307 oct 22 21:34 commands.sh
-rw-r--r-- 1 cseygflp csic    0 oct 22 21:34 non-eukaryota.scaffolds.list
-rw-r--r-- 1 cseygflp csic    0 oct 22 21:34 non-eukaryota.scaffolds_to_bins.tsv
-rw-r--r-- 1 cseygflp csic    0 oct 22 21:34 scaffolds_to_bins.tsv
```

At first I thought that my contigs weren't binning, but it stopped immediately. I do not think it had enough time to compute anything. Also, I just realized that the metabat2 error file points to `scaffolds_to_bins.tsv` not being in the `tmp` directory, but the error logfile from SLURM is looking for it in `intermediate/1__binning_metabat2`, where it doesn't exist either. Is this expected?

**Comment by jolespin** [comment]
Can you zip the whole `../analyses/veba_eukaryotic_binning/binning/nano.G2/nano.G2/` directory and upload it here so I can take a look?

**Comment by franlat** [comment]
I think I solved the issue. It wasn't VEBA, but my BAM files. Some headers were truncated at some step and metabat couldn't work with it. I found this by trying metabat2 independently, were an error was raised on the issue. I tried re-doing the mapping and it worked (at least the metabat part). It produced 4 bins but crashed due to memory limitations in the next step. 

I'll try again and see if it properly works (it seems so, but you never know)

Thank you for the help!

**Comment by jolespin** [comment]
Feel free to reopen this issue if you have any more problems!

I usually use 133GB of memory for the euk binning.  It's needed for MetaEuk.  In the future, I plan on developing a NextFlow implementation that efficiently allocates the memory for different steps in a workflow but right now it's sequential.

**Comment by franlat** [comment]
Yes, it was the BAM files, it finished a few hours ago and the output is the expected one! 

Thank you for your help @jolespin ! 
I'll close the thread

**Comment by jolespin** [comment]
Awesome!  Let me know if you have any questions on what to do next.  

One bit I want to point out is that the fungal biosynthetic gene cluster detection isn't working right now.  It's having a hard time parsing the ids so I'm working on a way around it.

**Comment by franlat** [comment]
Yes! I really like how the Veba-classify works. The micro eukaryotic database is great. Since these samples might have a lot of fungi, I'll wait to try the biosynthetic gene cluster. But for now, VEBA is making my life much easier in identifying eukaryotic MAGs!
