### ISSUE TITLE
[Question] Creating a tutorial for modular analysis 

### ISSUE THREAD

**Issue by erfanshekarriz** [jolespin/veba#6]
Dear Josh, 

Hope all is well. Erfan here again. I wanted to also kindly request for there to be tutorials for people hoping to insert themselves at a specific point of the pipeline. 

Since the pipeline is very structural, let's say I've done my assembly using different software, and now want to do my binning using your pipeline, I need to create many directories, and subdirectories, which can get confusing. 
In my case, I ran into an issue with the prokaryotic binning step. My code:

```
Python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)  [GCC 9.4.0]
Python path: /home/eshekarriz/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/python
Script version: 2022.10.26
VEBA Database: /home/eshekarriz/hdd_16t/database/veba
Moment: 2022-11-15 02:18:13
Directory: /home/eshekarriz/hdd_16t/analysis/SeepFungiNet2022/metagenomics/veba
Commands:
['/home/eshekarriz/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/binning-prokaryotic.py', '-f', 'veba_output/assembly/SMM2/output/scaffolds.fasta', '-b', 'veba_output/assembly/SMM2/output/mapped.sorted.bam', '-n', 'SMM2', '-p', '24', '-o', 'veba_output/binning/prokaryotic/', '-m', '1500', '-I', '10']

```

The error I got:
`Traceback (most recent call last):
  File "/home/eshekarriz/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/binning-prokaryotic.py", line 2380, in <module>
    main()
  File "/home/eshekarriz/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/binning-prokaryotic.py", line 2370, in main
    pipeline = create_pipeline(
  File "/home/eshekarriz/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/binning-prokaryotic.py", line 1859, in create_pipeline
    cmd = get_checkm_cmd(**params)
  File "/home/eshekarriz/miniconda3/envs/VEBA-binning-prokaryotic_env/bin/binning-prokaryotic.py", line 661, in get_checkm_cmd
    "--tmpdir {}".format(os.environ["TMPDIR"]), # Hack around: OSError: AF_UNIX path too long
  File "/home/eshekarriz/miniconda3/envs/VEBA-binning-prokaryotic_env/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'TMPDIR'`

I'm guessing this is because there are intermediate files that are created in the previous steps that I'm missing. Correct me if I'm wrong but I've also checked the source code and it seems like I should have a TMPDIR in my os environment that I don't have in check. 

Would appreciate your help and also perhaps tutorials on how to "insert" ourselves in a specific module from a different pipeline seamlessly. 

Best, 

Erfan

**Comment by jolespin** [comment]
>12. Why did I get a KeyError: 'TMPDIR'?
>
>This is because CheckM can't handle long directory paths. By default, the temporary directory is set to the TMPDIR environment variable. If you don't have a TMPDIR environment variable for some reason, add a TMPDIR environment variable to your path either in the script or your ~/.bash_profile. For example, `export TMPDIR=/path/to/temporary/directory/with/read/write/access


Does #12 from the [FAQ](https://github.com/jolespin/veba/blob/main/FAQ.md) help?

**Comment by erfanshekarriz** [comment]
> FAQ

Dear Josh, 

Apologize, I've completely missed that despite reading the FAQ. Still, I think the FAQ is a bit confusing since it has no explanation as to what TMPDIR is if you're not familiar with Linux. 

Would you advise we make a TMPDIR environmental variable in our VEBA conda environment folder? Or should we make a general one? Maybe a link to a tutorial would be helpful for others! 

Best, 

Erfan

**Comment by jolespin** [comment]
I've updated the FAQ with this info. 

>`TMPDIR` is the canonical environment variable in Unix and POSIX that should be used to specify a temporary directory for scratch space. Most Unix programs will honor this setting and use its value to denote the scratch area for temporary files instead of the common default of /tmp or /var/tmp.
>
>Source - https://en.wikipedia.org/wiki/TMPDIR

You can just set this to a scratch directory or anywhere really just as long as the path isn't too long.  CheckM errors out if the tmp directory path is too long which is why I added this in there. 

You can just add it to your home directory (given you have some storage there). 

```bash
mkdir -p /home/[username]/TMPDIR
echo 'export TMPDIR=/home/[username]/TMPDIR` >> ~/.bash_profile
```

This should do the trick^^^ 

You can also specify with the `--tmpdir` argument.
