### ISSUE TITLE
[Question] Retaining k-mer and non-kmer hits in the bbduk.sh  step of preprocess.py

### ISSUE THREAD

**Issue by erfanshekarriz** [jolespin/veba#7]
Dear Josh, 

I've found in the documentation of preprocess.py (v2022.01.19) There are two flags:

--retain_kmer_hits RETAIN_KMER_HITS
                        Retain reads that map to k-mer database. 0=No, 1=yes [Default: 0]
  --retain_non_kmer_hits RETAIN_NON_KMER_HITS
                        Retain reads that do not map to k-mer database. 0=No, 1=yes [Default: 0]

These two contradict each other. It's slightly confusing as to how by default this process **both** _does not retain kmer_ hits and also _does not retain non kmer hits_.  This to me translates into "does not keep any of the reads at all", which I don't see how it could be possible. 

I thought it might be a typo. If it is BBDuk lingo, some clarity in the walkthrough would be great.

Best, 

Erfan

**Comment by jolespin** [comment]
Check out the usage here, it might make more sense: https://github.com/jolespin/fastq_preprocessor/blob/630face4c434c7829eede6c4a728b82c96ca942a/fastq_preprocessor/fastq_preprocessor.py#L180

The intended usage here was to just quantify the number of k-mer hits (e.g., ribosomal reads). Since this use case is probably pretty niche, I provided an option to retain or remove them. In some cases somebody might want the filtered reads that do not have any k-mer hits but in many cases they are kept. 

```python
# BBDuk
def get_bbduk_cmd(input_filepaths, output_filepaths, output_directory, directories, opts):
    os.environ["TMPDIR"] = directories["tmp"]
    cmd = [ 
            "(",
        os.environ["bbduk.sh"],
        "zl=1", # Most likely will delete these files
        "overwrite=t",
        "threads={}".format(opts.n_jobs),
        "in1={}".format(input_filepaths[0]),
        "in2={}".format(input_filepaths[1]),
        "ref={}".format(opts.kmer_database),
        # "refstats={}".format(os.path.join(output_directory, "bbduk_refstats.txt")),
        # "stats={}".format(os.path.join(output_directory, "bbduk_stats.txt")),
        "k={}".format(opts.kmer_size),
        "minlen={}".format(opts.minimum_read_length),
        "out1={}".format(os.path.join(output_directory, "non-kmer_hits_1.fastq.gz")),
        "out2={}".format(os.path.join(output_directory, "non-kmer_hits_2.fastq.gz")),
        "outm1={}".format(os.path.join(output_directory, "kmer_hits_1.fastq.gz")),
        "outm2={}".format(os.path.join(output_directory, "kmer_hits_2.fastq.gz")),
        opts.bbduk_options,
        ")",

        # Seqkit
        "&&",
        "(",
        os.environ["seqkit"],
        "stats",
        "-T",
        "-j {}".format(opts.n_jobs),
        os.path.join(output_directory, "*.fastq.gz"),
        ">",
        os.path.join(output_directory, "seqkit_stats.tsv"),
        ")",
        ]


    # Remove bbduk kmer hits
    if not opts.retain_kmer_hits:
        cmd += [
        "&&",
        "rm -rf {}".format(os.path.join( output_directory, "kmer_hits_*.fastq.gz")),
        ]
    # Remove bbduk non-kmer hits
    if not opts.retain_non_kmer_hits:
        cmd += [
        "&&",
        "rm -rf {}".format(os.path.join( output_directory, "non-kmer_hits_*.fastq.gz")),
        ]

            
    return cmd
```

**Comment by jolespin** [comment]
Closing now, if it's still not clear then reopen and we can discuss it further. Cheers
