### ISSUE TITLE
[Typo] In Viral Metatranscriptomics Tutorial

### ISSUE THREAD

**Issue by erfanshekarriz** [jolespin/veba#8]
In the viral transcriptomic walkthrough:

CMD="source activate VEBA-assembly_env && assembly.py -1 ${R1} -2 ${R2} -n ${ID} -o ${OUT_DIR} -p ${N_JOBS} --P rnaspades.py"

The option tag should be -P instead of --P

A quick catch. Hope it helps.

Best, 

Erfan

**Comment by jolespin** [comment]
Thanks for catching that.  I added in `megahit` as an option so I wanted to change all the reference to `--spades_program` as `-P` but must have missed the double dash.  

Fixed here: https://github.com/jolespin/veba/commit/3104de007c9db2ee6fac0bf48e7584b90188b489
