### ISSUE TITLE
[Question] VEBA-biosynthetic_env/bin/mmseqs: No such file or directory

### ISSUE THREAD

**Issue by javiercnav** [jolespin/veba#84]
Hello there, first, yes, I have read the FAQ section :)
I am running the VEBA-biosynthetic pipeline, and the protocol fails at the 4__mmseq2_protein step.
When I check the log for this step, I get the following error:

/bin/bash: /projects/navarro_lab/envs/VEBA-biosynthetic_env/bin/mmseqs: No such file or directory

Also, I want to add that I reinstall VEBA to the latest release and when I do:
conda env list, I do not see VEBA-biosynthetic_env listed among my environments. Perhaps this is related to the mmseq issue?

Could you advice?
Bests!

**Comment by javiercnav** [comment]
Hello there, I have reinstalled VEBA to the current version and it all works well.
thank you!

**Comment by jolespin** [comment]
Excellent! Which version are you running? 

I'm going to close this issue.  Let me know if you have any more issues.

**Comment by javiercnav** [comment]
Hello, I am using version 2.0.0 and the VDB_v6.
Thank you for all your hard work!
