### ISSUE TITLE
How do I start with pre-filtered data ready to assemble?

### ISSUE THREAD

**Issue by kellyu01** [jolespin/veba#85]
Hello,
I will start by saying that I do not have much experience with coding, and I apologize if my question is very basic. 
I have data that has been filtered and is ready to assemble. I have only two files, 05_350.nohost.fq1.gz (forward) and 05_350.nohost.fq2.gz (reverse). I tried to run the following:

R1=/nohost/05_350.nohost.fq1.gz
R2=/nohost/05_350.nohost.fq2.gz
OUT_DIR= veba_output/assembly

CMD="source activate VEBA && veba --module assembly --params \"-1 ${R1} -2 ${R2} -o ${OUT_DIR} -p ${N_JOBS} -P metaspades.py\""

I did not get any errors, but simply nothing happened. I am not sure what I am doing wrong. Please help.

Thank you!

**Comment by jolespin** [comment]
No problem! I’d be glad to help. How did your installation go? 
 
Can you try this?
conda activate VEBA-assembly_env
assembly.py -h

**Comment by jolespin** [comment]
Feel free to reopen this.
