### ISSUE TITLE
[Feature Request] Expanding Viral Identification & Analysis Toolset

### ISSUE THREAD

**Issue by erfanshekarriz** [jolespin/veba#9]
Dear Josh, 

I hope all is well. Erfan again!

I wanted to suggest expanding the VEBA's viral binning toolkit. I specifically request this since you mentioned VEBA is there to speed up the ad-hoc commands of meta-omics pipelines. Viral assembly using multiple software is definitely one of the most troublesome since multiple software is needed to classify contigs and 

**_I've attached my personal pipeline for viral contig identification:_**
<img width="575" alt="viral omics" src="https://user-images.githubusercontent.com/95677856/204412042-e91e4ac6-3f9c-445c-8c51-781b2c1a3e3a.png">
* I now use Virsorter2
* DeepVirFinder is just a deep network version of VirFinder so it might be redundant

The assembly phase usually relies on more than one tool if you'd like to make a convincing argument about viral diversity (e.g. PPR-Meta is the only one that identifies phages with high accuracy). The output then needs integration to remove redundant sequences, pool contigs, perform consensus classification, and ultimately rename them for the sake of consistency and clarity (like which software it came from). All of which I think VEBA is there to resolve. 

I think this would give VEBA the edge in analyzing viral contigs in a well-structured manner, a field that I think is growing exponentially every day.  I think even including just CheckV, VirSorter2, DeepVirFinder/VirFinder, and PPR-Meta should be more than enough. 

Hope these help, and look forward to seeing VEBA grow. 

Best, 

Erfan

**Comment by jolespin** [comment]
I'll definitely take this into consideration.  My immediate plan for the viral binning was to incorporate geNomad (https://github.com/apcamargo/genomad) which works very well for viral detection and classification.  I have had trouble getting some of the other viral software to work (eg virsorter2) on different machines.  I also don't want to have too many databases because the db size for veba is already massive.

**Comment by erfanshekarriz** [comment]
Great to hear. I haven't heard of geNomad but I'll definitely have a look.

I'm currently finalizing a viral metagenomic paper and from my experience, reviewers of more critical journals expect at least 3 different sources of binning. I just see VirSorter2 (alignment based) and VirFinder (Ab Initio) being used most.

I'd recommend having a look at this paper as well. https://doi.org/10.1038/s41396-021-00932-y

Hope it helps and look forward.

Erfan

**Comment by jolespin** [comment]
That’s good to know and maybe VirSorter2 has changed since I last used.  I just remembered it being very clunky and buggy.  

I’ll give this paper a read.

Let me know when your pub comes out too.

**Comment by erfanshekarriz** [comment]
Just to update you on this, 

I found a new software for detecting phages (PhaMer) and tested it.
https://github.com/KennthShang/PhaMer
https://doi.org/10.1093/bib/bbac258

PPR-meta is quite difficult to install & requires MRC. PhaMer's publication shows that it performs better and it's easily conda installable. I will swap it out for PPR-meta from my personal pipeline as well.

Hope this helps, 

Best, 
Erfan

**Comment by jolespin** [comment]
Do you know if they plan on releasing a version through conda or PyPI? I'm currently only using packages that I can install directly through `conda install [package]` or `pip install [package]`.  The reason for this is that I already have a lot of packages each with a lot of dependencies so I need the install to be able to be a one-liner with all of the dependencies accounted for by conda or pip from the environment files.

**Comment by erfanshekarriz** [comment]
Quoting them directly: 

> Thanks for your suggestions. But maybe it is not necessary currently because we do not have many updates for the program. The future updates might be the database/parameters I suppose. Also, it seems using bioconda recipe won't save much time or reduce the progress of installing PhaMer. Using PhaMer.yaml directly might be much easier for new users. We might consider this when it is necessary.

I could easily install their software and run it using the PhaMer.yaml file. I'm not sure if they would release on the bioconda distribution anytime soon. 

Best, 

Erfan

**Comment by jolespin** [comment]
Just added an option to use `genomad` which is now the default.  Will be available in v1.1.
